About as
Serhii-Ivanchenko/project-Team-12 pull request #5
Opened 2024-01-12 12:49 UTC by DmitryLyakhivsky

Посмотри пожалуйста в моб версии текст стоит по центру
Как его растянуть на весь блок?

2024-01-12 22:18 UTC, Serhii-Ivanchenko commented on src/partials/about-us.html
> +<section class="container">
тут треба вказати клас section

2024-01-12 22:22 UTC, Serhii-Ivanchenko commented on src/partials/about-us.html
> +  <div class="about">
цей дів не потрібен взагалі

2024-01-12 22:27 UTC, Serhii-Ivanchenko commented on src/partials/about-us.html
> + <h2><span class="about-title">About</span><span class="us-title"> Us</span> </h2>
ці спани зайві, оформлення заголовків h2 прописане в базових стилях. Тільки Us має бути огорнуте в span з класом accent (це також базовий стиль для виділення тексту коричневим кольором).

2024-01-12 22:34 UTC, Serhii-Ivanchenko commented on src/partials/about-us.html
> +  <div class="wrapper-desktop">
цей дів не потрібен, для стилізації десктопної версії стилізуємо той же клас, що і для мобільної і для планшетної, просто через медіазапит

2024-01-12 22:39 UTC, Serhii-Ivanchenko commented on src/partials/about-us.html
> +  <div class="about-img">
цей дів не потрібен

2024-01-12 22:44 UTC, Serhii-Ivanchenko commented on src/partials/about-us.html
> +    ./img/about-us/about_us_mobile_2x.jpg 2x"
картинки в форматі webp мають бути в одному srcset, в форматі jpg в іншому srcset. Я в телеграмі тобі скину скріншот, як має виглядати тег picture.

2024-01-12 22:51 UTC, Serhii-Ivanchenko requested changes
pls fix

2024-01-14 11:21 UTC, DmitryLyakhivsky reviewed
Переделал

2024-01-14 17:26 UTC, Serhii-Ivanchenko approved these changes

2024-01-14 17:26 UTC, merged